# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Anct < Formula
  desc "📺 Unofficial CLI Client of Annict"
  homepage "https://arrow2nd.com/works/anct"
  version "1.3.5"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/arrow2nd/anct/releases/download/v1.3.5/anct_Darwin_x86_64.tar.gz"
      sha256 "5d6a6d3b603bcb765520490fa9b675dbb8fff25465d56ba9e319b459018d26f8"

      def install
        bin.install "anct"
      end
    end
    on_arm do
      url "https://github.com/arrow2nd/anct/releases/download/v1.3.5/anct_Darwin_arm64.tar.gz"
      sha256 "e0d47a37c9a0b739df3967d941748123e85c31827c74d122cf367445cd2037eb"

      def install
        bin.install "anct"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/arrow2nd/anct/releases/download/v1.3.5/anct_Linux_x86_64.tar.gz"
        sha256 "0a1626d651edfcd8541720146a274f77b7214283337bce50fff46ad4a832b132"

        def install
          bin.install "anct"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/arrow2nd/anct/releases/download/v1.3.5/anct_Linux_arm64.tar.gz"
        sha256 "91291038c19938508cd9af49f9d072d612eb94ebc0e2cd978236cf66f8f53c08"

        def install
          bin.install "anct"
        end
      end
    end
  end

  test do
    system "#{bin}/anct -v"
  end
end
