# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Anct < Formula
  desc "📺 Unofficial CLI Client of Annict"
  homepage "https://arrow2nd.com/works/anct"
  version "1.3.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arrow2nd/anct/releases/download/v1.3.6/anct_Darwin_x86_64.tar.gz"
      sha256 "efd1d47e67fdee841884c47fe334e0386111013485a5d224b322fdcd10fb68a1"

      def install
        bin.install "anct"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arrow2nd/anct/releases/download/v1.3.6/anct_Darwin_arm64.tar.gz"
      sha256 "ab7aed8d2e48fb3a5141874636b74d24e2876cd2ce4d500be1d9f00ab0181508"

      def install
        bin.install "anct"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/arrow2nd/anct/releases/download/v1.3.6/anct_Linux_x86_64.tar.gz"
        sha256 "a33112e2a1e4a60f918ab675983e7c3c3b52ef877d2f01342955d2c7cfcfbc68"

        def install
          bin.install "anct"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/arrow2nd/anct/releases/download/v1.3.6/anct_Linux_arm64.tar.gz"
        sha256 "70dbda0e7717428f5d1b050e2198c09edc231d56107face8ba77ebb4c4a86468"

        def install
          bin.install "anct"
        end
      end
    end
  end

  test do
    system "#{bin}/anct -v"
  end
end
