# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nimotsu < Formula
  desc "CLI tool to tracking packages in Japan 📦"
  homepage "https://arrow2nd.com/works/nimotsu"
  version "1.3.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arrow2nd/nimotsu/releases/download/v1.3.5/nimotsu_Darwin_x86_64.tar.gz"
      sha256 "995fac715ae1dda9a8ffba6dc2ae282b60b79e6c576714ac1ad86fa918787b66"

      def install
        bin.install "anct"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arrow2nd/nimotsu/releases/download/v1.3.5/nimotsu_Darwin_arm64.tar.gz"
      sha256 "5a7b742a04e27da2b935edfd7eddadb62eac44cb31813a6ea1bc5ef39c485533"

      def install
        bin.install "anct"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/arrow2nd/nimotsu/releases/download/v1.3.5/nimotsu_Linux_x86_64.tar.gz"
        sha256 "8e7810164cd3eef61b45a22ca84d85248c4078b84ddc428866ad10f45c3cf06b"

        def install
          bin.install "anct"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/arrow2nd/nimotsu/releases/download/v1.3.5/nimotsu_Linux_arm64.tar.gz"
        sha256 "aef21d6b559e7f0ffb02e53f4b69e090e7f832e079283ea859023485c4eb12bb"

        def install
          bin.install "anct"
        end
      end
    end
  end

  test do
    system "#{bin}/anct -v"
  end
end
