# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nimotsu < Formula
  desc "CLI tool to tracking packages in Japan 📦"
  homepage "https://arrow2nd.com/works/nimotsu"
  version "1.3.4"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/arrow2nd/nimotsu/releases/download/v1.3.4/nimotsu_Darwin_x86_64.tar.gz"
      sha256 "fe9ce5e71d24b965783c1cfbfe7e693b2d1952f295bfe6601b32c5f0e5c72849"

      def install
        bin.install "anct"
      end
    end
    on_arm do
      url "https://github.com/arrow2nd/nimotsu/releases/download/v1.3.4/nimotsu_Darwin_arm64.tar.gz"
      sha256 "58dc0302779d019f6aca8032a2581d409be5caf2a0defa72bc5625a9fa79e636"

      def install
        bin.install "anct"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/arrow2nd/nimotsu/releases/download/v1.3.4/nimotsu_Linux_x86_64.tar.gz"
        sha256 "6fbac09534aab6d1663c1c90808f163188b5d1212ec56ad7833e570fae95218f"

        def install
          bin.install "anct"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/arrow2nd/nimotsu/releases/download/v1.3.4/nimotsu_Linux_arm64.tar.gz"
        sha256 "b02db69e0d76eae8f2d39d7b04ae8012ef5f873c9543d73772832925be454971"

        def install
          bin.install "anct"
        end
      end
    end
  end

  test do
    system "#{bin}/anct -v"
  end
end
