# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Anct < Formula
  desc "📺 Unofficial CLI Client of Annict"
  homepage "https://arrow2nd.com/works/anct"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/arrow2nd/anct/releases/download/v1.0.0/anct_Darwin_arm64.tar.gz"
      sha256 "cd575d649550e67bf673ebbb93586be4687c0ed1398c10c93b5661ddfd15aa03"

      def install
        bin.install "anct"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/arrow2nd/anct/releases/download/v1.0.0/anct_Darwin_x86_64.tar.gz"
      sha256 "73d3dec58be24305c3cbad2847b3f8845b7c40acd292ce2a5794b4baaeb54185"

      def install
        bin.install "anct"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arrow2nd/anct/releases/download/v1.0.0/anct_Linux_arm64.tar.gz"
      sha256 "f97ad30e8ae05284211b387f10a92bf63892881f2f302a29df1ca81663685935"

      def install
        bin.install "anct"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/arrow2nd/anct/releases/download/v1.0.0/anct_Linux_x86_64.tar.gz"
      sha256 "06421e1b73fdfbf01c2702b4786a2b5eb302fe1455780182a28bd81fe6c6a873"

      def install
        bin.install "anct"
      end
    end
  end

  test do
    system "#{bin}/anct -v"
  end
end
