# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Codic < Formula
  desc "Unofficial CLI client of codic"
  homepage "https://arrow2nd.com/works/codic-cli"
  version "1.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arrow2nd/codic-cli/releases/download/v1.1.0/codic-cli_1.1.0_Darwin_x86_64.tar.gz"
      sha256 "faddb4aa2c07dd1a56a6b3164495165ad5c320a74d291e6de2fa58b4c386583f"

      def install
        bin.install "codic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arrow2nd/codic-cli/releases/download/v1.1.0/codic-cli_1.1.0_Darwin_arm64.tar.gz"
      sha256 "26c3a919a37911bf990c040749517bd633d8eac0173654941d9a5ff6b869e29e"

      def install
        bin.install "codic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/arrow2nd/codic-cli/releases/download/v1.1.0/codic-cli_1.1.0_Linux_x86_64.tar.gz"
      sha256 "daf39aafd1cefe01f4f435a6ab124de3a5dcd53baf812ee9c9d6b03281be25d9"

      def install
        bin.install "codic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arrow2nd/codic-cli/releases/download/v1.1.0/codic-cli_1.1.0_Linux_arm64.tar.gz"
      sha256 "1f222a5ce26ee2f38c539f7bde2568273a7a76312122a0734cc0e38b33dafecd"

      def install
        bin.install "codic"
      end
    end
  end

  test do
    system "#{bin}/codic -v"
  end
end
