# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Codic < Formula
  desc "Unofficial CLI client of codic"
  homepage "https://arrow2nd.com/works/codic-cli"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arrow2nd/codic-cli/releases/download/v1.0.0/codic-cli_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "665c1e49addb1fb273345d9024db8f9e47893c87c1bc8b5def42f7d38b7b3f18"

      def install
        bin.install "codic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arrow2nd/codic-cli/releases/download/v1.0.0/codic-cli_1.0.0_Darwin_arm64.tar.gz"
      sha256 "b9e7cd547142fadbeaea08653044e5f1bceeb03b38b1540c1ed38d0eb4268559"

      def install
        bin.install "codic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/arrow2nd/codic-cli/releases/download/v1.0.0/codic-cli_1.0.0_Linux_x86_64.tar.gz"
      sha256 "5336350d5b1bbf9bd86b4d3a826e43c83f7aac17dac55f2c2e2c5331f4898253"

      def install
        bin.install "codic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arrow2nd/codic-cli/releases/download/v1.0.0/codic-cli_1.0.0_Linux_arm64.tar.gz"
      sha256 "9acc236a11224cde50b2820790534425c76980ee10d11ec2b1d26df56c16861e"

      def install
        bin.install "codic"
      end
    end
  end

  test do
    system "#{bin}/codic -v"
  end
end
