# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jisyo < Formula
  desc "📚 SKK辞書マネージャ"
  homepage "https://arrow2nd.com/works/jisyo"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arrow2nd/jisyo/releases/download/v0.0.1/jisyo_Darwin_x86_64.tar.gz"
      sha256 "e5c26b18c776f82b7ea29db0b000ffb298c99e4d669253ccf650093008f68415"

      def install
        bin.install "jisyo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arrow2nd/jisyo/releases/download/v0.0.1/jisyo_Darwin_arm64.tar.gz"
      sha256 "22387b575b87ad39fc70cd13608655dc8a2b216c655d298e0800e8190143ed2e"

      def install
        bin.install "jisyo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arrow2nd/jisyo/releases/download/v0.0.1/jisyo_Linux_arm64.tar.gz"
      sha256 "d4d67d1d0a28409c039c55de6c3a1a8927347dbb928c1bf900879e435d145e85"

      def install
        bin.install "jisyo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/arrow2nd/jisyo/releases/download/v0.0.1/jisyo_Linux_x86_64.tar.gz"
      sha256 "2ee0641d5b52801faba82238d78fe2f6644486db309799b3dc02a08972e1d1bb"

      def install
        bin.install "jisyo"
      end
    end
  end

  test do
    system "#{bin}/jisyo -v"
  end
end
