# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nekome < Formula
  desc "TUI Twitter client 🐈"
  homepage "https://arrow2nd.com/works/nekome"
  version "0.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arrow2nd/nekome/releases/download/v0.0.0/nekome_0.0.0_Darwin_x86_64.tar.gz"
      sha256 "69b142784c8a2efc7231a16f48cfba80019e24ce12cd31312de5a08a0379e306"

      def install
        bin.install "nekome"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arrow2nd/nekome/releases/download/v0.0.0/nekome_0.0.0_Darwin_arm64.tar.gz"
      sha256 "7a84629fda32e0e420b1bcb3bde237c6290b44b8a767c7be1d25ebdeb1e4fd51"

      def install
        bin.install "nekome"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arrow2nd/nekome/releases/download/v0.0.0/nekome_0.0.0_Linux_arm64.tar.gz"
      sha256 "f7ea69036494af376d2e6fc45264ad9efd4afd233f912d14410651fd181dc565"

      def install
        bin.install "nekome"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/arrow2nd/nekome/releases/download/v0.0.0/nekome_0.0.0_Linux_x86_64.tar.gz"
      sha256 "337242dacaa9bed908f61ff293dc63f7e0d61bc6d167401c3076ffe73eebab90"

      def install
        bin.install "nekome"
      end
    end
  end

  test do
    system "#{bin}/nekome -v"
  end
end
