# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nekome < Formula
  desc "TUI Twitter client 🐈"
  homepage "https://arrow2nd.com/works/nekome"
  version "2.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arrow2nd/nekome/releases/download/v2.2.1/nekome_Darwin_x86_64.tar.gz"
      sha256 "cf6a0a698f96744c62cbdb1de01b61fe8a470b80feec98c48e9e8662049d7342"

      def install
        bin.install "nekome"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arrow2nd/nekome/releases/download/v2.2.1/nekome_Darwin_arm64.tar.gz"
      sha256 "34c3c67d4a0e4566098c395cc293395c8541c7bf327f8cb0b18b2b02bc77a783"

      def install
        bin.install "nekome"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arrow2nd/nekome/releases/download/v2.2.1/nekome_Linux_arm64.tar.gz"
      sha256 "6b3684acac5924d62a0e72cd67b33aaa6dfd5bc24fdaf6e4b689f422e201b240"

      def install
        bin.install "nekome"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/arrow2nd/nekome/releases/download/v2.2.1/nekome_Linux_x86_64.tar.gz"
      sha256 "9fee8cb5ed15eafcbb4e487faba18d028baef1679e4453164b6e269c51526ff6"

      def install
        bin.install "nekome"
      end
    end
  end

  test do
    system "#{bin}/nekome -v"
  end
end
