# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nimotsu < Formula
  desc "CLI tool to tracking packages in Japan 📦"
  homepage "https://arrow2nd.com/works/nimotsu"
  version "1.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arrow2nd/nimotsu/releases/download/v1.3.1/nimotsu_1.3.1_Darwin_x86_64.tar.gz"
      sha256 "5a6b405615e97f7c646c73d3dcc498ce95d8190763bb1221268fc615ef90c843"

      def install
        bin.install "nimotsu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arrow2nd/nimotsu/releases/download/v1.3.1/nimotsu_1.3.1_Darwin_arm64.tar.gz"
      sha256 "3c17f333b86d082c0117187bfd8ba04f5a65e5a980936b56843b2300a8adf52b"

      def install
        bin.install "nimotsu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arrow2nd/nimotsu/releases/download/v1.3.1/nimotsu_1.3.1_Linux_arm64.tar.gz"
      sha256 "015ffeb84d31e523c8d2a4f8ad72d681fee0d0d1d381ed171c16cf7ff9fc2aba"

      def install
        bin.install "nimotsu"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/arrow2nd/nimotsu/releases/download/v1.3.1/nimotsu_1.3.1_Linux_x86_64.tar.gz"
      sha256 "a8e75ccef981b13970c7fb1eb6b34acbaa0f64d0ec0f8e8fd7d3a9ac0f8f7acb"

      def install
        bin.install "nimotsu"
      end
    end
  end

  test do
    system "#{bin}/nimotsu ver"
  end
end
