# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nimotsu < Formula
  desc "CLI tool to track packages in Japan 📦"
  homepage "https://arrow2nd.com/works/nimotsu"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/arrow2nd/nimotsu/releases/download/v1.2.0/nimotsu_1.2.0_Darwin_arm64.tar.gz"
      sha256 "0ff750335b057f8780f54d2305a95f23bc0a0ac7d5c5f863dc5d98cd95fa5a54"

      def install
        bin.install "nimotsu"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/arrow2nd/nimotsu/releases/download/v1.2.0/nimotsu_1.2.0_Darwin_x86_64.tar.gz"
      sha256 "19aae66f351cf93be2a06b877d1c703748250970171b34e537222a41c716f3c7"

      def install
        bin.install "nimotsu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arrow2nd/nimotsu/releases/download/v1.2.0/nimotsu_1.2.0_Linux_arm64.tar.gz"
      sha256 "fc6c0958b336de6e3c3f6a9fcac04cb5a79da3d901f550eb46a82c237f9ce686"

      def install
        bin.install "nimotsu"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/arrow2nd/nimotsu/releases/download/v1.2.0/nimotsu_1.2.0_Linux_x86_64.tar.gz"
      sha256 "72de3ac3d6711d863335a359131c85ef82b3f96f4968c16e9129dd1057ae344d"

      def install
        bin.install "nimotsu"
      end
    end
  end

  test do
    system "#{bin}/nimotsu ver"
  end
end
