# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nimotsu < Formula
  desc "CLI tool to tracking packages in Japan 📦"
  homepage "https://arrow2nd.com/works/nimotsu"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/arrow2nd/nimotsu/releases/download/v1.3.0/nimotsu_1.3.0_Darwin_arm64.tar.gz"
      sha256 "c78adeadb7664a165934df43cb78e34abfe67935ded8229a450ccb902549867f"

      def install
        bin.install "nimotsu"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/arrow2nd/nimotsu/releases/download/v1.3.0/nimotsu_1.3.0_Darwin_x86_64.tar.gz"
      sha256 "73931003759ab036cc0aef8f2ab812cb0884c999fafb3532cd1a32078274e039"

      def install
        bin.install "nimotsu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/arrow2nd/nimotsu/releases/download/v1.3.0/nimotsu_1.3.0_Linux_x86_64.tar.gz"
      sha256 "19d094927c646144b5b477bc6c145a667bb71922b62c11ecdd83ef71822bda5d"

      def install
        bin.install "nimotsu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arrow2nd/nimotsu/releases/download/v1.3.0/nimotsu_1.3.0_Linux_arm64.tar.gz"
      sha256 "b07cb4553228c0c785413eefa6be76aa4615ccef2c7eccb9e85fcc2d815aa1f4"

      def install
        bin.install "nimotsu"
      end
    end
  end

  test do
    system "#{bin}/nimotsu ver"
  end
end
