# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Twnyan < Formula
  desc "Twitter client for Terminal🐾"
  homepage "https://arrow2nd.com/works/twnyan"
  version "1.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/arrow2nd/twnyan/releases/download/v1.6.0/twnyan_1.6.0_Darwin_arm64.tar.gz"
      sha256 "b3a6239c55bbe184385925aa93ca7528b8125c8bb2682aafa4304c0397cf8948"

      def install
        bin.install "twnyan"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/arrow2nd/twnyan/releases/download/v1.6.0/twnyan_1.6.0_Darwin_x86_64.tar.gz"
      sha256 "a772ed43f99fcc4ddb6d37a3d5ae42d44c489579e3ba714132ba48db559dbcec"

      def install
        bin.install "twnyan"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/arrow2nd/twnyan/releases/download/v1.6.0/twnyan_1.6.0_Linux_x86_64.tar.gz"
      sha256 "d5c056fc51a5ebad612addd2539dbbfb7da28625ebad6bc5e177f699724864c7"

      def install
        bin.install "twnyan"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arrow2nd/twnyan/releases/download/v1.6.0/twnyan_1.6.0_Linux_arm64.tar.gz"
      sha256 "9b2201dec677a3f2aa279b36629aa3cd9966e472fdca039427fcbb872a0bdf1f"

      def install
        bin.install "twnyan"
      end
    end
  end

  test do
    system "#{bin}/twnyan ver"
  end
end
