# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Twnyan < Formula
  desc "Twitter client for Terminal🐾"
  homepage "https://arrow2nd.com/works/twnyan"
  version "1.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arrow2nd/twnyan/releases/download/v1.9.0/twnyan_1.9.0_Darwin_x86_64.tar.gz"
      sha256 "1b8198102778fb1c96335579cebe43eabe88e06068d6810ff98513266fbf27ad"

      def install
        bin.install "twnyan"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arrow2nd/twnyan/releases/download/v1.9.0/twnyan_1.9.0_Darwin_arm64.tar.gz"
      sha256 "13cd40777d8b3b0dd61a37181e0239fc23c97e08cde80407cc3871825fb2ede5"

      def install
        bin.install "twnyan"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/arrow2nd/twnyan/releases/download/v1.9.0/twnyan_1.9.0_Linux_x86_64.tar.gz"
      sha256 "c54ec03a96d07f53b12032a0aad71812de8b044162d89cfa4613588b22ee8acc"

      def install
        bin.install "twnyan"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arrow2nd/twnyan/releases/download/v1.9.0/twnyan_1.9.0_Linux_arm64.tar.gz"
      sha256 "9ce4ee58e66ab258f5f1a7d9943c773741933a207f0580710a539f3d4843ca78"

      def install
        bin.install "twnyan"
      end
    end
  end

  test do
    system "#{bin}/twnyan ver"
  end
end
